# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Upload Checkstyle Results
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-results
        path: target/site/checkstyle.html
        
    - name: Run Junit tests
      run: mvn test --file pom.xml
    - name: Generate Test Report
      run: mvn surefire-report:report --file pom.xml

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: target/site/surefire-report.html
      
      
    - name: Package JAR
      run: mvn package --file pom.xml
    
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: target/*.jar
        
  
#     - name: Publish to GitHub Packages
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#          GITHUB_TOKEN: ${{ secrets.java_token }}
